version: "3.8"

networks:
  public:

volumes:
  db-data: {}

services:
  mayalokam-frontend:
    container_name: mayalokam-frontend
    image: php:8.0-apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - public

  mayalokam-db:
    container_name: mayalokam-db
    image: mysql:8.0
    ports:
      - 3306:3306
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_DATABASE=musicupload
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - public
