version: "3.8"

networks:
  public:

volumes:
  db-data: {}

services:
  mayalokam-frontend:
    container_name: mayalokam-frontend
    image: php:7.4-apache
    command: "/bin/sh -c 'docker-php-ext-install mysqli && exec apache2-foreground'"
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./data/php.ini:/usr/local/etc/php/conf.d/my.ini
      - ./musik:/var/www/html/musik
    networks:
      - public

  mayalokam-db:
    container_name: mayalokam-db
    image: mysql:8.0
    ports:
      - 3306:3306
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_DATABASE=musicupload
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    networks:
      - public

  mayalokam-phpmyadmin:
    container_name: mayalokam-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mayalokam-db
    networks:
      - public
